### PR TITLE
fix #312

### LINKED ISSUE #312: skinny-http-client can not parse `Set-Cookie` what contains path atribute
https://github.com/skinny-framework/skinny-framework/blob/99b1072bbe9c0b7ecfa903c9152a3d0e02ce444d/http-client/src/main/scala/skinny/http/HTTP.scala#L194-L195

```scala
            setCookie.split("=") match {
              case Array(name, _) => Some(name -> setCookie)
```

When `setCookie` contains `path` like as `Set-Cookie: foo=bar; path=/; HttpOnly`,
`setCookie.split("=")` returns an array that has 3 elements. `Array("foo", "bar; path", "/; HttpOnly")`

Should it `split("=", 2)` ?

### PR DESCRIPTION
**Pull request by gakuzzzz**
#312

### CODE REVIEW

**Comment by gakuzzzz** [comment]
Can we squash on GitHub in a browser?

**Comment by xuwei-k** [comment]
> Can we squash on GitHub in a browser?

Can't

**Comment by gakuzzzz** [comment]
please squash......

**Comment by seratch** [comment]
LGTM :+1: Please squash commits into one.

**Comment by seratch** [comment]
I just did squash.

**Comment by seratch** [comment]
Thank you for your contribution :+1:  @gakuzzzz

**Comment by gakuzzzz** [comment]
:pray:

**Pull request merged**
